baseURL       = "https://mg-editor-agent.fr/"
languageCode  = "en-us"
title         = "MG | Editor & Foreign Rights Agent"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Menu"
    url     = "/"
    weight  = 1
  [[menu.nav]]
    name    = "Éditorial"
    url     = "editorial"
    weight  = 3
  [[menu.nav]]
    name    = "Foreign Rights"
    url     = "foreign-rights"
    weight  = 4
  [[menu.nav]]
    name    = "Books"
    url     = "portfolio"
    weight  = 5
  [[menu.nav]]
    name    = "À propos"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Contactez-moi"
    url     = "contact"
    weight  = 7

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "MG | Editor | Agent | Foreign Rights | foreign rights agent| mg_editor_agent | Les petites moustaches | Le muscadier | Utopique | Scrineo | Lectrice | éditrice | Bordeaux | France | Psy Season | Family Kisses | Glows of Traverse | Staying Alive | Lucy | Little Stories of Fashion"
  author = "Mélanie Guillaumin | editor | agent | foreign rights agent"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  formspreeFormUrl  = "https://formspree.io/f/xayaqqok"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Prénom"
    placeholder_last_name         = "Nom"
    placeholder_email             = "Email"
    placeholder_project_type      = "Type de projet"
    placeholder_about_the_project = "Description du projet"
    send_message                  = "Envoyer"

    [[params.contactForm.projectType]]
      value = "lec"
      title  = "Lecture/Fiche de lecture"
    [[params.contactForm.projectType]]
      value = "Corr"
      title  = "Correction/Préparation de copie"
    [[params.contactForm.projectType]]
      value = "Rédac"
      title  = "Rédaction/Réécriture"
    [[params.contactForm.projectType]]
      value = "foreign rights"
      title  = "Foreign Rights"
    [[params.contactForm.projectType]]
      value = "autre"
      title  = "Autre"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/background-mg.png"
    heading               = "Vous aider à enrichir et promouvoir votre catalogue"
    tagline               = "DÉCOUVRIR, CONCEVOIR, DIFFUSER"
    primary_button        = "Éditorial"
    primary_button_url    = "editorial"
    secondary_button      = "Foreign Rights"
    secondary_button_url  = "foreign-rights"

  [params.portfolio]
    enable    = true
    title     = "NOVELTIES"
    subtitle = "Foreign Rights"


  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "MG Editor & Foreign Rights Agent"
      address = "74 avenue de Tivoli <br> 33110 Le Bouscat"
      phone   = "+ 33 6 23 36 11 02"
      email   = "melanie.guillaumin.edition@gmail.com"
      # Footer Social Media
      [params.footer.social]
        title   = "Actualités"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/mgeditorandagent/?hl=fr"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/company/mg-editor-foreign-rights-agent"
      # Footer Service
      [params.footer.service]
        title       = "Aider les éditeurs à"
        description = "trouver des projets <br>les mettre en forme<br>les promouvoir à l'étranger"
