baseURL       = "https://mg-editor-agent.fr/"
languageCode  = "en-us"
title         = "MG | Editor & Foreign Rights Agent"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Menu"
    url     = "/"
    weight  = 1

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = ""
  author = ""
  # Google Analitycs
  googleAnalitycsID = ""
  formspreeFormUrl  = "https://"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Prénom"
    placeholder_last_name         = "Nom"
    placeholder_email             = "Email"
    placeholder_project_type      = "Type de projet"
    placeholder_about_the_project = "Description du projet"
    send_message                  = "Envoyer"

    [[params.contactForm.projectType]]
      value = "lec"
      title  = "Lecture/Fiche de lecture"
    [[params.contactForm.projectType]]
      value = "Corr"
      title  = "Correction/Préparation de copie"
    [[params.contactForm.projectType]]
      value = "Rédac"
      title  = "Rédaction/Réécriture"
    [[params.contactForm.projectType]]
      value = "foreign rights"
      title  = "Foreign Rights"
    [[params.contactForm.projectType]]
      value = "autre"
      title  = "Autre"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/background-mg.png"
    heading               = "Vous aider à enrichir et promouvoir votre catalogue"
    tagline               = "DÉCOUVRIR, CONCEVOIR, DIFFUSER"
    primary_button        = "Éditorial"
    primary_button_url    = "editorial"
    secondary_button      = "Foreign Rights"
    secondary_button_url  = "foreign-rights"

  [params.portfolio]
    enable    = true
    title     = ""
    subtitle = ""


  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = ""
      address = ""
      phone   = ""
      email   = ""
      # Footer Social Media
      [params.footer.social]
        title   = ""
        [[params.footer.social.link]]
          name = ""
          url  = ""
        [[params.footer.social.link]]
          name = ""
          url  = ""
      # Footer Service
      [params.footer.service]
        title       = ""
        description = ""
